# Generated by Django 4.1.5 on 2023-01-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_genre', models.CharField(help_text='Enter a movie genre (e.g. Action)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=225)),
                ('movie_rating', models.CharField(max_length=10, null=True)),
                ('launch_date', models.DateTimeField(null=True, verbose_name='date launched')),
                ('price', models.IntegerField(default=0)),
                ('sale_currency', models.CharField(choices=[('Kshs', 'Kenya Shillings')], default='Kshs', max_length=10)),
                ('sku', models.CharField(default=0, max_length=5)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moviecatalog.moviegenre')),
            ],
        ),
    ]
